class PostsController < ApplicationController
  def index
    ## we declare an instance variable @posts and assign it a collection of Post objects using the all method provided by ActiveRecord
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
# #9 we call Post.new to create a new instance of Post
    @post = Post.new
    @post.title = params[:post][:title]
    @post.body = params[:post][:body]

  # #10 if we successfully save Post to the database, we display a success message using flash[:notice] and redirect the user to the route generated by @post
    if @post.save
  # #11 we assign a value to flash[:notice]
      flash[:notice] = "Post was saved."
      redirect_to @post
    else
  # #12 if we do not successfully save Post to the database, we display an error message and render the new view again
      flash.now[:alert] = "There was an error saving the post. Please try again."
      render :new
    end
  end

  def edit
  end
end
